require'settings'.init()
require'mappings'.init()
-- plugins
require'plugins.indentline'.init()
require'plugins.cmp'.init()
require'plugins.lualine'.init()
require'plugins.telescope'.init()
require'plugins.treesitter'.init()
require'plugins.colorscheme'.init()
require'plugins.nvimtree'.init()
require'plugins.formatting'.init()
require'plugins.toggleterm'.init()
require'plugins.lsp'.init()
require'plugins.luasnip'.init()
