#!/bin/sh
# XDG PATHS
export XDG_CONFIG_HOME=$HOME/.config
export XDG_CACHE_HOME=$HOME/.cache
export XDG_DATA_HOME=$HOME/.local/share

# Path exports
export PATH=$PATH/neovim/build/bin
export TERM="xterm"
export VISUAL="nvim"
export EDITOR=$VISUAL
export PATH=/snap/bin:$PATH
export PATH=$PATH:/usr/local/go/bin
export PATH=$PATH:$HOME/go/bin
export PATH=$PATH:$HOME/.rvm/bin
export PATH=$PATH:/.yarn/bin
export PATH=$PATH:/usr/local/android-studio/bin
export PATH=$PATH:$ANDROID_SDK

HISTFILE=$XDG_DATA_HOME/zsh/history
HISTSIZE=10000000
SAVEHIST=10000000

